### ISSUE TITLE
Import error in check.py

### ISSUE THREAD

**Issue by tama-mononoke** [ProfHoekstra/bluesky#105]
I appreciate you for providing an open ATC simulator to researchers who cannot use expensive simulators. 
I manually installed the required libraries such as PyQt4 and PyOpenGL in my Windows (Windows 7, 32 bit) and tried to launch BlueSky in  OpenGL mode, but I failed. So, I launched check.py in order to check whether the required libraries are appropriately installed, but I got the following error message:

F:\Installed\Folder\bluesky-20170323>python check.py
This script checks the availability of the libraries required by BlueSky, and th
e capabilities of your system.

Checking for numpy               [OK]
Checking for scipy               [OK]
Checking for matplotlib          [OK]
Checking for pyqt                [QT4]
Checking for pyopengl            [OK]
OpenGL module version is         [3.1.0]
Checking GL capabilities         [OK]
GL Version at least 3.3          [OK]
Supported GL version             [3.3]
Checking for pygame              [OK]

You have all the required libraries to run BlueSky. You can use both the QTGL an
d the pygame versions.
Checking bluesky modules
Using Qt4 for windows and widgets
StateBasedCD: using default Python version, no compiled version for this platfor
m.
Using BlueSky performance model
Traceback (most recent call last):
  File "check.py", line 139, in <module>
    from bluesky.traf.params import *
ImportError: No module named params

One or more BlueSky modules are not working properly, check the above error for
more detail.

The following is the error message I got when I launched BlueSky.py.

Initializing multi-process simulation
QGLWidget initialized for OpenGL version 3.3
Loading global navigation database...
Reading cache: navdata.p
Reading cache: rwythresholds.p
Reading cache: aptsurface.p
Maximum supported texture size: 8192
Loading texture data/graphics/world.8192x4096.dds
Traceback (most recent call last):
  File "F:\Installed\Folder\bluesky-20170323\bluesky\ui\qtgl\radarwidget.py", line 42
5, in initializeGL
    print 'Error while creating RadarWidget objects: ' + e.args[0]
IndexError: tuple index out of range

**Comment by jooste** [comment]
I see that you are running a version of bluesky of a couple of months back, so it may be useful to first download the current source. Since you are having problems in the OpenGL part of bluesky it could also be a graphics hardware issue. What videocard do you use?

**Comment by tama-mononoke** [comment]
I appreciate for your quick reply, Joost.
Following your advice, I got the latest source files from the master branch. Check.py was successfully finished.

However, I still fail to launch bluesky. New error messages are:

(First)
  File "F:\atc\bluesky\bluesky-20170905\bluesky-master\bluesky\ui\qtgl\glhelpers
.py", line 52, in create_empty_buffer
    gl.glBufferData(target, size, None, usage)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (sr
c\latebind.c:1201)
  File "c:\users\masato\appdata\local\enthought\canopy32\user\lib\site-packages\
OpenGL\GL\VERSION\GL_1_5.py", line 89, in glBufferData
    return baseOperation( target, size, data, usage )
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__
(src\latebind.c:989)
  File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__ (s
rc\wrapper.c:6561)
  GLError: GLError(
        err = 1285,
        description = '\x83\x81\x83\x82\x83\x8a\x95s\x91\xab',
        baseOperation = glBufferData,
        pyArgs = (
                GL_ARRAY_BUFFER,
                160000000,
                None,
                GL_STREAM_DRAW,
        ),
        cArgs = (
                GL_ARRAY_BUFFER,
                160000000,
                None,
                GL_STREAM_DRAW,
        ),
        cArguments = (
                GL_ARRAY_BUFFER,
                160000000,
                None,
                GL_STREAM_DRAW,
        )
)

(Second)
  File "F:\atc\bluesky\bluesky-20170905\bluesky-master\bluesky\simulation\qtgl\n
odemanager.py", line 23, in run
    connection = Client(('localhost', 6000), authkey=b'bluesky')
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-1.6.2.3262.win-x8
6\lib\multiprocessing\connection.py", line 169, in Client
    c = SocketClient(address)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-1.6.2.3262.win-x8
6\lib\multiprocessing\connection.py", line 308, in SocketClient
    s.connect(address)
  File "C:\Program Files\Enthought\Canopy32\App\appdata\canopy-1.6.2.3262.win-x8
6\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10061] Connection refused. No connection could be made because the target computer actively refused it.

They seem memory shortage and network problem. My graphiccard is Intel HD Graphics 4400. Any advice is welcome.

**Comment by jooste** [comment]
GL error 1285 is indeed an out of memory error. Try the following change:
in bluesky/ui/qtgl/radarwidget.py, line 57, remove the '* 1000'. You can also try reducing the other MAX_... values there.

The network problem can be something separate, but may also result from the gui not starting properly.

**Comment by tama-mononoke** [comment]
I appreciate your kind advice. 
I changed MAX_TRAILLEN  with MAX_NAIRCRAFT * 100.
Then, bluesky was successfully launched.
