### ISSUE TITLE
Should the metrics block in the stack be pulled out?

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#11]
The metrics block in the stack file needs to be adapted every time a metric is added.

Isn't it better to move the metrics command processing to the metrics module so the stack file doesn't have to be changed on the addition or change of a metric?

**Comment by ProfHoekstra** [comment]
Yes, add the command to the dictionary, just like the CRE (create) command and have it point to a function in the metrics block.
