### ISSUE TITLE
Restoration of TCP conn functionality

### ISSUE THREAD

**Issue by reube** [ProfHoekstra/bluesky#111]
Please see pull request: https://github.com/ProfHoekstra/bluesky/pull/110

thx Andrew

**Comment by jooste** [comment]
Hi Andrew,

Can you explain a bit more why you need reply's to every tcp command? Is this an implementation thing on the client side, or a timeout issue?

Thanks!

**Comment by reube** [comment]
Hi Joost.  Its helpful to have explicit feedback as a (tcp) client for any of the actions, including those that are 'puts/sets' rather then 'gets'.  Ie, for writing control scripts against bluesky using the tcp interface.
Thx A

**Comment by reube** [comment]
merged https://github.com/ProfHoekstra/bluesky/commit/88747635265d9f2e72ff4ab967c990ad12c7cdee
