### ISSUE TITLE
Waypoint names are rendered wrong

### ISSUE THREAD

**Issue by jacobythwaites** [ProfHoekstra/bluesky#112]
If I `pan liffy`, it appears in the display as `FYLIF`

Screenshot attached.
![bug](https://user-images.githubusercontent.com/2727822/32551626-100a7fde-c489-11e7-9218-6ad9786155d7.png)

Platform is Mac OS X 10.13, using QtGL, bluesky master branch.

**Comment by jooste** [comment]
Thanks! This was caused by one waypoint in the database being longer than five characters :). Fixed in 9fe1c81.
