### ISSUE TITLE
DELWPT fails if one waypoint added

### ISSUE THREAD

**Issue by jacobythwaites** [ProfHoekstra/bluesky#113]
To replicate, perform these commands:
```
CRE EZ833 B739 n53'04'34.0 w011'12'0.0 82 35000 250
ADDWPT EZ833 LIFFY 16000
LISTRTE EZ833
DELWPT EZ833 LIFFY
```
The waypoint is not deleted, even though it is listed (screenshot enclosed).
![bug](https://user-images.githubusercontent.com/2727822/32556245-d1e21060-c496-11e7-8706-9aee367ca135.png)

**Comment by jooste** [comment]
This was a bug for routes with only one waypoint. Solved in ded64bc.
