### ISSUE TITLE
`AT` altitude and speed change command only affects altitude

### ISSUE THREAD

**Issue by miklosduma** [ProfHoekstra/bluesky#116]
Hi Again,

The `AT` command now works a treat if you edit the altitude speed constraints separately.

If you try to override both altitude and speed at the same time though, it ignores the speed override.

E.g.

```
Foo ADDWPT std 20000 320
Foo AT std ALT 18000 SPD 300
```
Will change the altitude constraint to 18000 but leave the speed constraint at 320.

Thanks for the super-quick fixes :)

**Comment by jooste** [comment]
Hi,

This is not currently how the command is parsed (but maybe it should). Currently, if you want to set both altitude and speed you would have to do:
    Foo AT std 18000/300
However, when I was testing this I found some irregularities in the actual LNAV/VNAV logic: the constraints are updated in the route (shown e.g., by listrte), but they are not consistently followed.
Stay tuned for a fix :)

**Comment by ProfHoekstra** [comment]
Indeed the format of the AT command for combined speed and altitude constraint is "KL204 AT WOODY FL070/250", which is similar to the ADDWPT way to specify speed and altitude

In our testscenarios the VNAV logic (speed/alt) works, but we have now also identified some cases (maybe when there is no orig/dest specified?) where VNAV speed seems to be lost. I'm currently looking a these cases to fix this.

**Comment by miklosduma** [comment]
Thanks guys, staying tuned for the fixes. When I was testing `ADDWPT` and `AT` I did not specify `ORIG` and `DEST`.  I tend to just add the destination as the final waypoint, with a zero alt/spd constraint. Not sure of course whether I'm using your tool as you intended :)

**Comment by ProfHoekstra** [comment]
VNAV needs to be enabled, then it should work in normal routes

We also fixed a new issue with switching off VNAV that we found with a route of only one waypoint or a route ending mid-air.

**Comment by jooste** [comment]
Hi, this should indeed work when LNAV/VNAV is on. Commits 7399863 and 132d103 include additional fixes to the guidance logic for these cases with an incomplete route. An example to use for testing is scenario `testscenarios/LNAV-VNAV-nodestorig.scn` from commit 9dc9530.

**Comment by ProfHoekstra** [comment]
We've added an [ATALT](https://github.com/ProfHoekstra/bluesky/wiki/ATALT 
) command [ATSPD.](https://github.com/ProfHoekstra/bluesky/wiki/ATSPD 
) 

Your exanple would thus become:

Foo ATALT 18000 SPD 300
