### ISSUE TITLE
about FLIGHT PHASES

### ISSUE THREAD

**Issue by Jane3380** [ProfHoekstra/bluesky#121]
Hi 

I‘m confused with some codes in  “bluesky/bluesky/traffic/performance/legacy/performance.py”

“vmcr” has two different meanings?

![unnamed1](https://user-images.githubusercontent.com/34363111/33752641-ef80558e-dc1d-11e7-9883-edd63f6ffa7a.png)
![unnamed2](https://user-images.githubusercontent.com/34363111/33752642-efb2e9c2-dc1d-11e7-990b-d9e58b875fb3.png)

**Comment by isabelmetz** [comment]
Hi Jane3380,

 "vmcr" stands for minimum cruise speed. The allocation of flight phases is, among others, depending on that speed. Thanks to your question I see that there is an error in the comment in line 108, it should be 

# phase LD[5]: alt<3000, Speed below vmap (i.e. minimum approach speed) + 10kt.

I will correct the line.

If you would like to see the full documentation of the allocation of flight phases, please refer to the BADA User Manual, page 19 (page 39 in pdf view) https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiB5aPZjfrXAhVL1BoKHQvTAIUQFggnMAA&url=https%3A%2F%2Fwww.eurocontrol.int%2Fsites%2Fdefault%2Ffiles%2Ffield_tabs%2Fcontent%2Fdocuments%2Fsesar%2Fuser-manual-bada-3-12.pdf&usg=AOvVaw24nDn6Uf8jk15oCE_62sSl

Best, 
Isabel

**Comment by Jane3380** [comment]
I got it.

Thanks.
