### ISSUE TITLE
Aircraft created through `mcre` seem to share the same route

### ISSUE THREAD

**Issue by miklosduma** [ProfHoekstra/bluesky#123]
Hello Guys,

Seem to have run into an issue. 

To reproduce:
(assume for the minute that the new aircraft objects will be `foo` and `bar`
```
$ mcre 2
$ addwpt foo coa
$ listrte bar
*COA : ----/----
```
The waypoint `COA` was assigned only to `foo`, not `bar`, so running `listrte` on `bar` should not return it. Except of course, if this is the intended behaviour :)

Cheers!

**Comment by ProfHoekstra** [comment]
That is not intended behaviour! :)

Thanks, seems like an MCRE issue indeed!

Best regards,
    Jacco Hoekstra


On 12 Dec 2017, at 18:12, miklosduma <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Guys,

Seem to have run into an issue.

To reproduce:
(assume for the minute that the new aircraft objects will be foo and bar

$ mcre 2
$ addwpt foo coa
$ listrte bar
*COA : ----/----


The waypoint COA was assigned only to foo, not bar, so running listrte on bar should not return it. Except of course, if this is the intended behaviour :)

Cheers!

**Comment by jooste** [comment]
Hi all,

Easy fix :) See e219de4.

Cheers,
Joost
