### ISSUE TITLE
Unable to load the example plugin

### ISSUE THREAD

**Issue by 3isenHeiM** [ProfHoekstra/bluesky#127]
I'm trying to get the `example.py` plugin working (which adds a `MYFUN` command to the stack).
However, the `PLUGINS` command is not recognized, and I cannot manage to load it.
Here's the output on the command window :
`>> PLUGINS`
`Unknown command or aircraft: PLUGINS`

I've placed the file `example.py` in a "plugins" folder, inside the BlueSky root folder.
Moreover, I've mentioned it in the enabled_plugins inside the settings.cfg files...

Have I missed something ?

Thanks :)

**Comment by jooste** [comment]
From what I can see in the code, plugins should also work in the pygame version. Are you running the current version of bluesky?

**Comment by ProfHoekstra** [comment]
Yes, ‘plugins’ command works in the pygame version as well as it is the same code for command processing.

Just tested it to be sure: it works.

- Jacco

**Comment by jooste** [comment]
Thanks for the check! Pygame has been giving me issues since the latest version of Macos, so I can't test the pygame version myself.
