### ISSUE TITLE
how can I get the result of the simulation

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#136]
I'm currently working on several  simulations with  different speeds.For example, in 1000 simulations, the speed in each simulation is the same,but different between different simulations. The aircraft, waypoint, origin and destination are all the same among different simulations. In each simulation, I want to find out the deviation of the speed, altitude,logitude from each waypoint. How can I do that? Or where can I find the simulation results?

**Comment by YingxiaoKong** [comment]
just find out by myself, we can use snaplog to do that.

**Comment by jooste** [comment]
Hi YingxiaoKong,

Indeed, the basic state variables can be logged periodically with the snaplog. And if you want to log other properties that are not in the default loggers you can always create a new logger. The easiest way to do this is in a plugin. You can look at the area.py plugin for an example.

**Comment by davidlinardy** [comment]
> just find out by myself, we can use snaplog to do that.

is snaplog a command that we write in the .py file? i still don't understand how to operate the snaplog command.

i am working on an aircraft movement simulation in the terminal control area. I need to get the distance data between the aircraft to know the separation.

**Comment by jooste** [comment]
> > just find out by myself, we can use snaplog to do that.
> 
> is snaplog a command that we write in the .py file? i still don't understand how to operate the snaplog command.
> 
> i am working on an aircraft movement simulation in the terminal control area. I need to get the distance data between the aircraft to know the separation.

Hi David,

It depends what you want to log. To periodically log data (most often aircraft states), you can create a logger using the CRELOG command. For example:

    CRELOG MYLOG 1.0
    MYLOG ADD lat, lon, alt, tas, gs, hdg, asas.inconf
    MYLOG ON

would create a periodic logger that logs once per second the variables `lat`, `lon`, `alt`, `tas`, `gs`, `hdg`, `asas.inconf`
