### ISSUE TITLE
weird problems

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#137]
now I'm try to build the simplest case. Suppose I have define an orig, a destination. After the aircraft reaches the destination, it won't stop, it just continue going on and the simulation won't stop too. How can I stop the aircraft at that point and stop the simulation?

Besides, I have read that if I want to do 1000 simulations at the same time, I can generate 1000 nodes. But how can I do that?

**Comment by jooste** [comment]
Hi YingxiaoKong,

To delete aircraft when reaching the destination you could try to use the area plugin, and use it with an area definition with a lower altitude bound close to 0ft. This plugin automatically deletes aircraft that leave the area, so this should give you the functionality that you need.
