### ISSUE TITLE
Problem of generating airport binary file

### ISSUE THREAD

**Issue by junzis** [ProfHoekstra/bluesky#14]
It seems the binary file generation code is not working with pyQt4.. Maybe we should deprecated the support for qt4 ?...

Also, on Ubuntu the PyQt5 is only bundled with Python3. We have to built it from source code again. I think we could put out an guide on building pyqt5 on Mac and Linux.

--

Loading texture data/graphics/world.16384x8192.dds
Traceback (most recent call last):
  File "/home/junzi/workspace/py/bluesky/bluesky/ui/qtgl/radarwidget.py", line 679, in event
    self.airportsInRange()
  File "/home/junzi/workspace/py/bluesky/bluesky/ui/qtgl/radarwidget.py", line 610, in airportsInRange
    indices = np.logical_and.reduce((self.apt_ctrlat >= self.panlat - ll_range, self.apt_ctrlat <= self.panlat + ll_range,
AttributeError: 'RadarWidget' object has no attribute 'apt_ctrlat'

**Comment by ProfHoekstra** [comment]
Or is this because I just moved the docs folder to a subfolder in info? I was lost every time when I looked for the docs, because there I expect to find what was now info. - Jacco

**Comment by jooste** [comment]
Fixed in commit 9c5b85c
