### ISSUE TITLE
trajectory prediction using  secondary radar data 

### ISSUE THREAD

**Issue by taherihamza** [ProfHoekstra/bluesky#144]
HI, I discovered bluesky when looking for ways to implement a recorded trajectory data extracted from radar in a prediction model using machine learning, the data are in ASTERIX format, can bluesky afford that, if yes, how can I preceed.

**Comment by ProfHoekstra** [comment]
Dear Hamza,

Yes, but not yet plug-and-play. When you have the specification of the data format, that should be easy via a plug-in. Such a plug-in is not yet available and would be a nice addtion. Could you say which record you would like to import and how?

Another, maybe even better, option is to simply make a converter which converts it to a .scn file, see examples in scenario folder for the format and use the command reference on the Wiki.

Best regards,
    Jacco Hoekstra
