### ISSUE TITLE
Reading Config

### ISSUE THREAD

**Issue by webermak** [ProfHoekstra/bluesky#146]
the console does not seems to read the config from the updated settings.cfg &
the program crashes when HELP PDF is typed

**Comment by webermak** [comment]
the program crashes when HELP PDF is typed

**Comment by jooste** [comment]
Hi,

Can you give more details? What have you entered in the config file that is ignored?
The config file is read on startup of BlueSky, not afterwards.

**Comment by webermak** [comment]
Hi,

I changed the starting location of the radar screen and the airport_file

**Comment by jooste** [comment]
I don't know what you mean by airport_file. I also don't know of issues with setting start_location in the settings file. Are you running the current version of BlueSky? And on what system?

**Comment by webermak** [comment]
Running the latest version. BlueSky-win64-setup-20170323 on Win 10
the airport_file is for[ # indicate the location of the airport database]
- I edited the airport database to only contain airports of certain countries. 

I have tried deleting the setting file to see if it will cause and error when the program starts.
May I ask what should be the expected result if there is no setting file?

Thanks for your assistance

**Comment by jooste** [comment]
if there is no settings file it will use the default values.

You are using a bundled version of BlueSky (which is pretty old; we should make new bundles!). This creates a folder $HOME/bluesky. The config file you should edit is $HOME/bluesky/settings.cfg.

On windows, $HOME is generally something like: c:\Users\yourusername\

**Comment by webermak** [comment]
ohhh thanks, i think that explains it. 
would u suggest i use the latest version by compiling the source code? 
i have a bit of programming background in C# but am new to python language

**Comment by jooste** [comment]
Well, python is an interpreted language, so you don't have to compile anything. All you need is an installation of python (>= 3.5), and the required packages for BlueSky, see also the installation instructions on the [BlueSky wiki](https://github.com/ProfHoekstra/bluesky/wiki/Installation).
