### ISSUE TITLE
how to change the pressure and temperature by scn file

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#149]
Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location? 
 
By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by ProfHoekstra** [comment]
The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
    Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by YingxiaoKong** [comment]
Prof. Hoekstra,

Thank you so much for your reply and suggestion! I will have a look at ISA right now.

Best regards,
Yingxiao

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by YingxiaoKong** [comment]
Prof, Hoekstra,

I have tried your suggestion: to change the speed of the aircraft to simulate the engine broke down. and it works! But I want to make it more realistic: like what will be the real effect of  the engine broken down to the change of the speed?  I have found the engines.scv in the file and want to find out the influence if I changed some value of a parameter, but the thing is that I really don’t know the meaning of these parameters. I tried to search on line but didn’t get something useful. Can you give me some guidance to this? That will definitely be a great help to me and my research!

I’m looking forward to your reply!

Best regards,
YK

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by ProfHoekstra** [comment]
There is no difference between an idle engine and a broken engine. The aircraft models do not integrate the forces into accelerations, but you could still try to set the thrust to zero and see what the effect of the performance limits will be.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 7 Apr 2018, at 01:28, YingxiaoKong <notifications@github.com<mailto:notifications@github.com>> wrote:

Prof, Hoekstra,

I have tried your suggestion: to change the speed of the aircraft to simulate the engine broke down. and it works! But I want to make it more realistic: like what will be the real effect of the engine broken down to the change of the speed? I have found the engines.scv in the file and want to find out the influence if I changed some value of a parameter, but the thing is that I really don’t know the meaning of these parameters. I tried to search on line but didn’t get something useful. Can you give me some guidance to this? That will definitely be a great help to me and my research!

I’m looking forward to your reply!

Best regards,
YK

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by YingxiaoKong** [comment]
Prof. Hoekstra,

Thanks for your advice! I have tried to change the “bpr” parameter, I guess it is something to do with trust. And it make no difference to the arrival time.

Best,
YK

On Apr 7, 2018, at 3:49 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

There is no difference between an idle engine and a broken engine. The aircraft models do not integrate the forces into accelerations, but you could still try to set the thrust to zero and see what the effect of the performance limits will be.

Best regards/Met vriendelijke groeten,
Jacco Hoekstra


On 7 Apr 2018, at 01:28, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Prof, Hoekstra,

I have tried your suggestion: to change the speed of the aircraft to simulate the engine broke down. and it works! But I want to make it more realistic: like what will be the real effect of the engine broken down to the change of the speed? I have found the engines.scv in the file and want to find out the influence if I changed some value of a parameter, but the thing is that I really don’t know the meaning of these parameters. I tried to search on line but didn’t get something useful. Can you give me some guidance to this? That will definitely be a great help to me and my research!

I’m looking forward to your reply!

Best regards,
YK

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by ProfHoekstra** [comment]
Dear Yangxao Kong,

The model is kinematic, so it will try to fly the commanded speed. The performance limits should limit the maximum speed. To still fly the commanded speed without thrust, it would descent rapidly, which is not what a pilot would allow happening. So even with the right parameter, you still need to adjust the speed yourself. If you also set the ‘ALT alt, v/s’ the behaviour will be equal to an engine failure. So there is no need to tweak the performance model.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 8 Apr 2018, at 00:46, YingxiaoKong <notifications@github.com<mailto:notifications@github.com>> wrote:

Prof. Hoekstra,

Thanks for your advice! I have tried to change the “bpr” parameter, I guess it is something to do with trust. And it make no difference to the arrival time.

Best,
YK

On Apr 7, 2018, at 3:49 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

There is no difference between an idle engine and a broken engine. The aircraft models do not integrate the forces into accelerations, but you could still try to set the thrust to zero and see what the effect of the performance limits will be.

Best regards/Met vriendelijke groeten,
Jacco Hoekstra


On 7 Apr 2018, at 01:28, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Prof, Hoekstra,

I have tried your suggestion: to change the speed of the aircraft to simulate the engine broke down. and it works! But I want to make it more realistic: like what will be the real effect of the engine broken down to the change of the speed? I have found the engines.scv in the file and want to find out the influence if I changed some value of a parameter, but the thing is that I really don’t know the meaning of these parameters. I tried to search on line but didn’t get something useful. Can you give me some guidance to this? That will definitely be a great help to me and my research!

I’m looking forward to your reply!

Best regards,
YK

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by YingxiaoKong** [comment]
Dear Prof. Hoekstra,

Thank you so much for your guidance! Now I’m trying to simulate the the anomaly using bluesky. There are so many different kind of anomalies and they could happen at any time. Like the engine failure during cruising, descending, the wet road surface, the extreme weather, the mistake made by the pilot. The problem is, I don’t know how to reflect these anomaly in bluesky… I can use the speed change to simulate the engine anomaly, but what about the loss of control of the airplane?  They can also be reflected by the speed anomaly. And so many other anomaly can all be reflected by speed anomaly when anomaly hanppens, so how tell I tell which anomaly may lead to the speed anomaly as they can all cause the speed anomaly?

Another question is that when I’m simulating the collision between different aircrafts, when I turned down the ASAS and RESO, the airplane will collide with each other, but how can I know when they collide if I don’t stare at the screen all the time?


I’m looking forward to your reply!

Best regards,
Yingxiao Kong

On Apr 8, 2018, at 12:55 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Yangxao Kong,

The model is kinematic, so it will try to fly the commanded speed. The performance limits should limit the maximum speed. To still fly the commanded speed without thrust, it would descent rapidly, which is not what a pilot would allow happening. So even with the right parameter, you still need to adjust the speed yourself. If you also set the ‘ALT alt, v/s’ the behaviour will be equal to an engine failure. So there is no need to tweak the performance model.

Best regards/Met vriendelijke groeten,
Jacco Hoekstra


On 8 Apr 2018, at 00:46, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Prof. Hoekstra,

Thanks for your advice! I have tried to change the “bpr” parameter, I guess it is something to do with trust. And it make no difference to the arrival time.

Best,
YK

On Apr 7, 2018, at 3:49 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

There is no difference between an idle engine and a broken engine. The aircraft models do not integrate the forces into accelerations, but you could still try to set the thrust to zero and see what the effect of the performance limits will be.

Best regards/Met vriendelijke groeten,
Jacco Hoekstra


On 7 Apr 2018, at 01:28, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Prof, Hoekstra,

I have tried your suggestion: to change the speed of the aircraft to simulate the engine broke down. and it works! But I want to make it more realistic: like what will be the real effect of the engine broken down to the change of the speed? I have found the engines.scv in the file and want to find out the influence if I changed some value of a parameter, but the thing is that I really don’t know the meaning of these parameters. I tried to search on line but didn’t get something useful. Can you give me some guidance to this? That will definitely be a great help to me and my research!

I’m looking forward to your reply!

Best regards,
YK

On Apr 5, 2018, at 11:08 PM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

The distance is given in nautical miles, a standard aeronautical unit for distances, 1852 m and 1/60 of a degree latitude (so one minute).

There is a feature to have an offset temperature in the ISA (I’ll look it up, you can also check yourself).

To simulate an engine failure one would simply change the speed (and optionally give an altitude command with a V/S) at a waypoint (AT) at an altitude (ATALT) or at a given speed (ATSPD).

Best regards,
Jacco Hoekstra


On 6 Apr 2018, at 03:31, YingxiaoKong <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi Goost,

Do you know how I can change the air pressure and temperature by scn file? and how to let the airplane's engine run badly at a certain location?

By the way , when I'm using the DIST function to get the distance between 2 locations, the unit is"nm", is it the nano meter? Why it is so small?

**Comment by YingxiaoKong** [comment]
Thanks Prof. Hoekstra! I will try that later!

On Apr 9, 2018, at 1:19 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

Loss of separation, you can know by using the data logging, see the wiki on that. Also writing a plug-in to both generate and log plug-ins is an option. See the example template for that in the plug-in folder.

**Comment by YingxiaoKong** [comment]
Hi Prof. Hoekstra,

When I’m doing the simulation, I use ‘FF’ ti do it. Now I’m wondering how fast is it? There is also a ‘FF10S’ option, which means it is 10 times faster. But I still have no idea of this one.


Best,
Yingxiao

在 2018年4月9日，上午1:19，ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> 写道：

Loss of separation, you can know by using the data logging, see the wiki on that. Also writing a plug-in to both generate and log plug-ins is an option. See the example template for that in the plug-in folder.

**Comment by jooste** [comment]
`FF` runs the simulation as fast as your computer can calculate. `FF 10` does the same, but reverts to real-time running after 10 seconds.
