### ISSUE TITLE
Trigger on Landing

### ISSUE THREAD

**Issue by remonvandenbrandt** [ProfHoekstra/bluesky#153]
Hi,

I would like to record the time at which an aircraft touches-down, and then re-run the simulation with slightly modified parameters. Is it possible to define these kinds of triggers?

**Comment by ProfHoekstra** [comment]
Dear Remon,

Yes, that is definitely possible.

There are many ways in which you can do that. The best way is to make a plug-in, using the example plug-in. Detecting a landing can be done by checking the a/c state or flight phase if you’re following a specific aircraft or the area command (with an altitude) if it is a specific airport. You can define an event based logger or write or signal it yourself in the plug-in.

So please check: Traffic object, Plug-in and Data logging in the wiki.

Best regards,
    Jacco Hoekstra


On 8 Jun 2018, at 16:06, remonvandenbrandt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I would like to record the time at which an aircraft touches-down, and then re-run the simulation with slightly modified parameters. Is it possible to define these kinds of triggers?

**Comment by remonvandenbrandt** [comment]
I got the plugin and logger working, however I bumped into an error. When I create a flightplan which contains a large number of waypoints (100+) BlueSky seems to crash.

> Traceback (most recent call last):
  File "/mnt/UserData/x/repo/bluesky/bluesky/network/client.py", line 120, in receive
    self.stream(strmname, pydata, sender_id)
  File "/mnt/UserData/x/repo/bluesky/bluesky/ui/qtgl/guiclient.py", line 77, in stream
    self.stream_received.emit(name, data, sender_id)
  File "/mnt/UserData/x/repo/bluesky/bluesky/tools/signal.py", line 15, in emit
    subs(*args, **kwargs)
  File "/mnt/UserData/x/repo/bluesky/bluesky/ui/qtgl/radarwidget.py", line 616, in on_simstream_received
    self.update_route_data(self.routedata)
  File "/mnt/UserData/x/repo/bluesky/bluesky/ui/qtgl/radarwidget.py", line 639, in update_route_data
    update_buffer(self.routebuf, routedata)
  File "/mnt/UserData/x/repo/bluesky/bluesky/ui/qtgl/glhelpers.py", line 58, in update_buffer
    gl.glBufferSubData(target, offset, data.nbytes, data)
  File "latebind.pyx", line 44, in OpenGL_accelerate.latebind.Curry.__call__ (src/latebind.c:1201)
  File "/home/x/.local/lib/python3.6/site-packages/OpenGL/GL/VERSION/GL_1_5.py", line 125, in glBufferSubData
    return baseOperation( target, offset, size, data )
  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (src/latebind.c:989)
  File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6561)
  File "wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__ (src/wrapper.c:6439)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glBufferSubData,
	pyArgs = (
		GL_ARRAY_BUFFER,
		0,
		2096,
		array([49.185413 ,  8.87275  , 48.618332 ,  9.259167 , 52.304565 ,
        4.777535 , 52.296665 ,  4.7419443, 52.2966...,
	),
	cArgs = (
		GL_ARRAY_BUFFER,
		0,
		2096,
		array([49.185413 ,  8.87275  , 48.618332 ,  9.259167 , 52.304565 ,
        4.777535 , 52.296665 ,  4.7419443, 52.2966...,
	),
	cArguments = (
		GL_ARRAY_BUFFER,
		0,
		2096,
		array([49.185413 ,  8.87275  , 48.618332 ,  9.259167 , 52.304565 ,
        4.777535 , 52.296665 ,  4.7419443, 52.2966...,
	)
)

**Comment by jooste** [comment]
Hi Remon,

This is something we still need to catch properly: you are trying to show a route that has more waypoints than allocated memory for it in the gui. A quick fix would be to increase the value in `bluesky/ui/qtgl/radarwidget.py` line 57.

**Comment by remonvandenbrandt** [comment]
Increasing the allocated memory fixes bluesky from crashing, however I'm experiencing another bug when the number of waypoints are high. For some reason, the ac fails to climb to the set altitude. 

My scn file starts like this

> 00:00:00.00>SPD KLM65L 280 
00:00:00.00>ALT KLM65L Fl390 
00:00:00.00>KLM65L VNAV on 

When a small number of waypoints is present, the ac climbs to fl390, however when I add more waypoints, the ac doesn't climb beyond 1000ft or so.

If I manually set the alt after loading the scn file, the ac will climb to the set flight level, it seems like some part of the scn file is not read, or is being overwritten.

If attached a sample scn file: [516575.txt](https://github.com/ProfHoekstra/bluesky/files/2101448/516575.txt)

.

**Comment by jooste** [comment]
There's a couple of reasons why this happens. First, when you do `ALT FL390` before `VNAV ON`, then the altitude (autopilot) command gets overridden by the FMS VNAV mode. A better way to set an altitude in your route is to add it as a constraint to a waypoint in your route: `ADDWPT KL001 51,4,FL390`. You need to make sure though that the altitude is reachable in the remaining distance to that waypoint, since these constraints are not carried over to following waypoints. To be safe you can always repeat altitude constraints over multiple waypoints.

**Comment by YingxiaoKong** [comment]
Hi Remon,

I'm also doing something similar to yours. I want to find out with different approaching  altitude and speed, what's the probability that the aircraft will run out of the runway. As I can get the altitude of the aircraft using 'pos aircraft'. If the altitude of the runway has reached the altitude of the aircraft, it means that the aircraft touches down. 

But I'm not sure whether this is correct. That would be a great help if you could share your plugins with me. I'm still a green hands of python and I have no experience of doing this kind if things. I really need some example of how others doing something.

**Comment by YingxiaoKong** [comment]
Hi Remon,

actually I think if the airplane is approaching the airport, you can use' pos airport'name' to find out the altitude of the airport, and then check the output file that whether the airplane has reached the altitude of the airport or not. 

By the way, I'm also doing something similar to yours. That would be a great help if you can share your plugin with  me. I'm a green hand on python and has no experience of modifying the plugins. I really don't know how I can start.
