### ISSUE TITLE
Window not resizing properly 

### ISSUE THREAD

**Issue by RubenJacobse** [ProfHoekstra/bluesky#154]
When starting BlueSky all seems fine, but when resizing the main window the ?radarwidget? does not change. (QT 5.6.2, OpenGL 3.3)

Initial state:
![bs_start](https://user-images.githubusercontent.com/32992187/41604033-86693314-73de-11e8-86ad-41e8acf4cd88.png)

Resized state:
![bs_resize](https://user-images.githubusercontent.com/32992187/41604030-8554acba-73de-11e8-8104-030a6e2aff6f.png)

**Comment by jooste** [comment]
Thanks for the tip! Fixed in 34e0bab.
