### ISSUE TITLE
how can I speed up the decrease of the speed?

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#157]
Hi,

When I want to decrease the horizontal speed, I find out that the acceleration seems to be constant as -1knots/s all the time. Is there any other way I can do to change that? I want to have different acceleration in oder to simulate different situations.

**Comment by ProfHoekstra** [comment]
It’s dependent on the performance of the aircraft. In a plug-in, you can change everything, also that.

**Comment by YingxiaoKong** [comment]
Hi Joost,

I think I have asked this kind of question earlier, and I want to change the performance of one aircarft. I changed the parameter in the csv file which is related to the enigne, but nothing changed at all.

On Jun 20, 2018, at 9:34 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

It’s dependent on the performance of the aircraft. In a plug-in, you can change everything, also that.

**Comment by jooste** [comment]
Acceleration is currently just a fixed value that only depends on whether the aircraft is on the ground or not. It is not model-dependent yet. If you need more control over acceleration the easiest thing to do, I think, would be to change the traf.perf.acceleration() function in your fork.

**Comment by YingxiaoKong** [comment]
Hi Joost,

I have checked my computer but I could not find the traf.perf.accleration() you mentioned before. Do you mean that I shall write this on my won?

Best,
Yingxiao

On Jun 20, 2018, at 9:34 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:

It’s dependent on the performance of the aircraft. In a plug-in, you can change everything, also that.

**Comment by jooste** [comment]
This depends on which performance implementation you are using (there currently are three different ones in BlueSky). Look in bluesky/traffic/performance.
