### ISSUE TITLE
Improper deletion of drawn polygons

### ISSUE THREAD

**Issue by RubenJacobse** [ProfHoekstra/bluesky#158]
Polygons (and possibly also other drawing objects, but not tested) are not properly deleted from the radarwidget when using "DEL".  

When multiple polygons are drawn and later deleted, the deletion results seem to depend on the order of deletion (possibly also order of drawing). 

Example scenario:

0:00:00.00>PAN 0.0 0.00000
 
 0:00:01.00>POLY POLY001,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0
 0:00:02.00>POLY POLY002,2.0,-2.0,2.0,2.0,-2.0,2.0,-2.0,-2.0,0.0,0.0
 0:00:03.00>POLY POLY003,3.0,-3.0,3.0,0.0,-3.0,0.0,-3.0,-3.0
 
 0:00:05.00>DEL POLY001
 0:00:06.00>DEL POLY002
 0:00:07.00>DEL POLY003

**Comment by jooste** [comment]
Thanks!
Fixed in cd56861.
