### ISSUE TITLE
speed of the airplane won't decrease when it reached some values and how can I run without GUI

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#159]
Hi Joost,

Below is my scenario file:
00:00:00.00>SNAPLOG ON,1
00:00:00.00>CRE REP1,B744,36.2,-86.7659,135.20,3300 400
00:00:00.00> PAN KBNA
00:00:01.00>SPD REP1 10
00:00:01.00>ALT REP1 599
00:00:00.00>CRE REP2,B744, 36.117195,-86.686839 17.49 599 0
00:00:10.00>SPD REP2 200
00:00:10.00>ALT REP2 1000
00:02:10.00> quit

I don't know why the speed of the aircraft won't decrease  when it reaches 120 knots, no matter how much time I give it.

Also, the initial altitude for the aircraft is not 3300ft.  It always starts from around 800 ft. Is it because the system need sometime to increase the altitude of the aircraft?

Besides, now I'm trying to run bluesky without GUI with the command: python BlueSky.py --sim --detached --config-file settings.cfg --scenfile scenario.scn. But the GUI still appears.... And no result is given. Is there any thing I can do to fix this problem?

Looking forward to your reply!

**Comment by jooste** [comment]
Hi YingxiaoKong,

Your aircraft probably won't reduce below that speed because your selected speed is below the minimum operating speed.
I also can't seem to replicate your problem with the starting altitude: when I run your scenario file the aircraft correctly starts at an altitude of 3300 ft. I am also able to start the simulator in detached mode. Are you running the current version of bluesky?

**Comment by jooste** [comment]
Yes, I get a log file.

**Comment by YingxiaoKong** [comment]
Hi Joost,

Could you send me your setting.cfg and command? And what’s the minimum operation speed in bluesky?

Thank you so much!

Best,
Yingxiao

在 2018年6月27日，上午10:28，Joost Ellerbroek <notifications@github.com<mailto:notifications@github.com>> 写道：


Yes, I get a log file.

―

**Comment by jooste** [comment]
Hi Yingxiao,

I use the default settings, so if you just remove your own settings file you will have the same configuration as I have. The minimum operating speed is aircraft type specific.
