### ISSUE TITLE
openap doesn't work well

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#161]
Hi Joost,

When I'm trying to use openap to run some simulation. For single scenario file, it works perfectly. But when I'm using 'batch' to run a bunch of files, it just stoped running at the first few scenario files. I have check the memory of my computer, still 118 GB l?ft. So is it because of my computer or something else?

**Comment by jooste** [comment]
Hi YingxiaoKong,

There is not enough information to determine what is going wrong for you. What do you mean by 'stopped running'? Does bluesky crash? You also mention openap, do you get different behaviour when you use a different performance model?
