### ISSUE TITLE
Imposing Miles in Trail Restrictions

### ISSUE THREAD

**Issue by FireWithin** [ProfHoekstra/bluesky#168]
Hi everyone,

I am new to BlueSky and I am not sure if this is the best place to ask. 
I am working on some algorithms for ATM where I need to set Miles in Trail (MIT) values for aircrafts approaching a fix. I wish to run the simulation for particular settings of MIT and record delays and sectorwise congestion values after sometime.

I wanted to know if this possible, and if it is then how should this be approached?

Many thanks,
Aditya

**Comment by jooste** [comment]
Hi Aditya,

I'm sure all of the things you mention are possible, although I don't think I fully understand what your implementation implies. My thoughts on the different things you mention:

- MIT restrictions on approaching aircraft: Do you mean that depending on some minimum or maximum for miles in trail you place waypoints to achieve a certain remaining route length?

- Recording values like delays when aircraft land (or exit your simulation) is possible. If you look at the AREA plugin you can see an implementation that deletes aircraft as soon as they leave a certain area. Upon deletion several flight statistics are logged for that aircraft.

- Sector congestion count: have a look at the sectorcount plugin. I think this does pretty much what you need.

**Comment by FireWithin** [comment]
Hi,

Many thanks for a quick reply!
I will definitely look into the plugins you mentioned. 

About the MIT part: 
We wish to put fixes on specific entry points to a sector. These fixes will determine the minimum allowed MIT value for aircrafts approaching from outside (going downstream into the sector). So, when some MIT restriction is imposed at a fix, we require the simulator to slow down aircrafts approaching that particular fix or increase their ground delay (if they are still on ground) so as to follow up the restrictions. This will have implications on the delays and congestion in the sector which we need to record post simulation.

Please feel free to ask for any more details if need be.

Thank you for your time,
Aditya

**Comment by jooste** [comment]
Ok, I think the simplest way to implement is would be to create a plugin that knows the entry points with MIT constraints, and keeps track of aircraft with that entry point in their route. The plugin can periodically calculate MIT for the relevant aircraft, and if necessary adjust the airspeed using autopilot SPD commands. Such an implementation would not require modifications in the main bluesky code, only a plugin.
