### ISSUE TITLE
detached

### ISSUE THREAD

**Issue by netoeuc** [ProfHoekstra/bluesky#170]
Dear all,

I had some problems trying to run the simulation in **"detached"** mode. The return was:

```
File "~bluesky-master-2/bluesky/simulation/qtgl/simulation.py", line 32, in __init__
    settings.simstream_port)

TypeError: __init__() takes 1 positional argument but 3 were given
```

In order to solve it, I had a look into the **simulation.py** file and found out that it was instancing a **detached Node**:

```
super(SimulationClass, self).__init__(settings.simevent_port,
                                                  settings.simstream_port)
```

However,  only one parameter is expected (bluesky/network/detached.py):

```
class Node(object):
    def __init__(self):
        ...
```

Thus, I changed this line to:
```
class Node(object):
    def __init__(self, *args):
        ...
```
After that, I was able to run it. For example:

`$ python BlueSky.py --detached  --scenfile 0-Takeoff.scn`

Hope this suits you.

Kind Regards,
Neto.

**Comment by jooste** [comment]
Good suggestion, thanks! Implemented in ec47067.
