### ISSUE TITLE
Turn off AC interactions

### ISSUE THREAD

**Issue by MTMesfum** [ProfHoekstra/bluesky#179]
Hi,

I'm using BlueSky for my thesis and using a plugin developed by Remon.
However the plugin keeps crashing with the following error;

![image](https://user-images.githubusercontent.com/46937551/51910033-55ba0400-23ce-11e9-847d-4762e5c7b0fd.png)

The error is raised when I introduce a second aircraft (it won't even spawn).
It has been suggested to me that the issue can be circumvented if I turn off aircraft interactions.
I've tried running it with "ASAS OFF", but this isn't sufficient.
Are there any other interactions which could prevent this issue?

Kind regards,

Johannes

**Comment by jooste** [comment]
Hi Johannes,

The problem seems to be in traffic.windiris, which is also part of Remon's fork. Maybe @remonvandenbrandt can help you here?

**Comment by MTMesfum** [comment]
Hi Joost,

Remon finished his project and left already.
I've sent him an email as well, so I hope he'll still respond.

But I've tried to resolve the error myself and I think it's working.
The results seem to be consistent as well.
Is it possible for us to meet so we can discuss my approach?
I would appreciate a second opinion.

Kind regards,

Johannes

**Comment by jooste** [comment]
Hi Johannes,

Sure, I assume you are graduating with TUD? Just send me an email and we'll schedule a meeting!
