### ISSUE TITLE
OpenGL.error.GLError

### ISSUE THREAD

**Issue by QwertyJack** [ProfHoekstra/bluesky#2]
I'm using:
- win8.1 
- [Python(x,y)-2.7.10.0](http://python-xy.github.io/downloads.html)
- [pygame-1.9.1.win32-py2.7](http://pygame.org/download.shtml)

Can't see anything but a black board. Here is my log:

	Traceback (most recent call last):
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 276, in initializeGL
	    self.create_objects()
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 121, in create_objects
	    self.achdgbuf    = RenderObject.create_empty_buffer(MAX_NAIRCRAFT * 4, usage=gl.GL_STREAM_DRAW)
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 211, in create_empty_buffer
	    buf_id = gl.glGenBuffers(1)
	  File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.__call__ (D:\Build\PyOpenGL\pyopengl-bzr\OpenGL_accelerate\src\latebind.c:992)
	  File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__ (D:\Build\PyOpenGL\pyopengl-bzr\OpenGL_accelerate\src\wrapper.c:6564)
	OpenGL.error.GLError: GLError(
	        err = 1281,
	        description = '\xce\xde\xd0\xa7\xd6\xb5',
	        baseOperation = glGenBuffers,
	        pyArgs = (1, <object object at 0x01F984D0>),
	        cArgs = (1, array([2], dtype=uint32)),
	        cArguments = (1, array([2], dtype=uint32))
	)
	Traceback (most recent call last):
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\nd.py", line 179, in initializeGL
	    self.create_objects()
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\nd.py", line 144, in create_objects
	    self.waypoints = RenderObject.copy(self.shareWidget.waypoints)
	AttributeError: 'RadarWidget' object has no attribute 'waypoints'

Thanks for help :)

**Comment by jooste** [comment]
Hi Jack,

Can you tell me a bit more about your computer? laptop/desktop, CPU brand/model, graphics card?

**Comment by ProfHoekstra** [comment]
Dear Jack,

Did you try the Pygame version? This works on most systems and has less requirements on your graphics hardware as everything runs on your CPU in a single thread (which is also the main drawback, but it works fine up to reasonable numbers of aircraft in your scenario).

You can start it by using the BlueSky-Pygame.py or you could delete the settings.cfg file and choose pygame.

Best regards,
    Jacco Hoekstra


On 2 nov. 2015, at 17:23, jack <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm using:

  *   win8.1
  *   Python(x,y)-2.7.10.0[http://python-xy.github.io/downloads.html]
  *   pygame-1.9.1.win32-py2.7[http://pygame.org/download.shtml]

Can't see anything but a black board. Here is my log:

Traceback (most recent call last):
File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 276, in initializeGL
self.create_objects()
File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 121, in create_objects
self.achdgbuf = RenderObject.create_empty_buffer(MAX_NAIRCRAFT * 4, usage=gl.GL_STREAM_DRAW)
File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\glhelpers.py", line 211, in create_empty_buffer
buf_id = gl.glGenBuffers(1)
File "latebind.pyx", line 32, in OpenGL_accelerate.latebind.LateBind.call (D:\Build\PyOpenGL\pyopengl-bzr\OpenGL_a
ccelerate\src\latebind.c:992)
File "wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.call (D:\Build\PyOpenGL\pyopengl-bzr\OpenGL_acc
elerate\src\wrapper.c:6564)
OpenGL.error.GLError: GLError(
err = 1281,
description = '\xce\xde\xd0\xa7\xd6\xb5',
baseOperation = glGenBuffers,
pyArgs = (1, ),
cArgs = (1, array([2], dtype=uint32)),
cArguments = (1, array([2], dtype=uint32))
)
Traceback (most recent call last):
File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\nd.py", line 179, in initializeGL
self.create_objects()
File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\qtgl\nd.py", line 144, in create_objects
self.waypoints = RenderObject.copy(self.shareWidget.waypoints)
AttributeError: 'RadarWidget' object has no attribute 'waypoints'

Thanks for help :)

**Comment by QwertyJack** [comment]
My laptop is **TOSHIBA L600-05s**, which has **Intel i5 M430** and **ATI Radeon HD 4500 Series**.

I'v tried pygame version, but :
	C:\Users\jack\Downloads\bluesky\bluesky-master>python BlueSky-pygame.py
	Reading config from settings.cfg
	Using Qt4 for windows and widgets
	Traceback (most recent call last):
	  File "BlueSky-pygame.py", line 2, in <module>
	    from bluesky.ui.pygame import Gui
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\pygame\__init__.py", line 1, in <module>
	    from gui import Gui
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\pygame\gui.py", line 2, in <module>
	    from screen import Screen
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\pygame\screen.py", line 15, in <module>
	    from dialog import fileopen as opendialog
	  File "C:\Users\jack\Downloads\bluesky\bluesky-master\bluesky\ui\pygame\dialog.py", line 7, in <module>
	    from Tkinter import *
	  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
	    import FixTk
	  File "C:\Python27\lib\lib-tk\FixTk.py", line 65, in <module>
	    import _tkinter
	ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。
The last line means *Is not an effective Win32 Application*.

Thanks all.

**Comment by ProfHoekstra** [comment]
Dear Jack,

The error seems to be caused by a mix between 32-bits Python and a remaining 64-bits version on your PC of the Python Tkinter libs.

Make sure you remove the 64-bits installation completely. If necessary manually delete the entire Python folder, before installing the 32-bits version.

Tkinter is a standard Python library which should work on any functioning Python installation. It is used for the file open dialog box.

By the way, normally  I start the pygame version by simply double clicking the BlueSky-pygame.py.

Best regards,
     Jacco Hoekstra

**Comment by jooste** [comment]
Hi Jack,

According to [wikipedia](https://en.wikipedia.org/wiki/List_of_AMD_graphics_processing_units#Radeon_R700_.28HD_4xxx.29_Series), your videocard should be able to support OpenGL 3.3, which is also the minimum requirement for the GL version of BlueSky. I have added a test script to the trunk (also attached to this message, but as a txt file because github doesn't allow me to attach .py files
[gltest.txt](https://github.com/ProfHoekstra/bluesky/files/25915/gltest.txt)
). This script opens a basic GL window and writes a file called opengl-test.txt. This file contains information about the OpenGL support on your computer. Could you try to run that script and post the results from the resulting txt file?

Thanks!

**Comment by QwertyJack** [comment]
I remove all python installed before and reinstall python-xy, and it works !!!
Thanks a million **Prof.  Hoekstra** and thanks **jooste**.
I really appreciate your help :)

**Comment by jooste** [comment]
Hi Jack,

That's good to hear! Do both versions (pygame and opengl) work now?

64-bits incompatibility comes from pygame, which is only 32-bits. Other than that it should work.

**Comment by QwertyJack** [comment]
Ver. of **pygame** works, but **qtgl** still has the problem of *OpenGL.error 1281*, just as the very first post.

**Comment by QwertyJack** [comment]
Dear Mr.Jooste
I just test another computer: win2008server with **matrox g200eW**.
Version of pygame works perfectly but ***qtgl*** still not. I test *gltest*; it seems the test fails.
[qtgl.log](https://github.com/QwertyJack/Bluesky/blob/master/qtgl.log) is the log file when trying *qtgl* of BlueSky.
[opengl_test.txt](https://github.com/QwertyJack/Bluesky/blob/master/opengl_test.txt) is the *gltest* result, and [opengl_test.log](https://github.com/QwertyJack/Bluesky/blob/master/opengl_test.log) is the log file when testing.

Anyway, I guess this server does't support *qtgl* at all. I stiill wonder why *qtgl* fails on my laptop.

**Comment by jooste** [comment]
Hi Jack,

OpenGL 3.3 support is available on ATI/AMD/nVidia cards from around 2008/2009 and newer, and Intel IGP's from the haswell generation and newer.

If google is correct then your Matrox g200eW is from 1998, and therefore definitely too old.
Your laptop, however, should be able to support all of the OpenGL functions we use, which is also reported by the gltest.py script that you've used. I have just made a commit to BlueSky that adds additional checks to the initialization function for the opengl widgets, and which restarts the initialization with a delay if necessary. Could you perhaps try that on your laptop and let me know what it prints to the console? I've added a print statement that gives a message each time an invalid context is encountered in the initialization function.

Thanks!

**Comment by QwertyJack** [comment]
Dear Joose,

Thanks to your effort, Qtgl works perfectly on my laptop : )
Your help was greatly appreciated.

**Comment by jooste** [comment]
For sake of completeness in this thread: In the end this error had to do with the max supported texture size being smaller than a previous texture load attempt. QGLWidget.bindTexture does not present the error by default (pyOpenGL does), which is why the error passed by unnoticed. It did, however, leave the OpenGL in an error state, which affected the calls afterwards. The fix now checks explicitly for max supported texture size, and loads the appropriate texture.
