### ISSUE TITLE
more packages needed

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#3]
The `check.py` script should also check for the following:

* `python-qt5`
* `pyopengl`

And I had to re-install PyQt4.

At least these are the ones I had to install on top of the ones listed by `check.py`.
I am using Python 2.7.5

**Comment by jooste** [comment]
You're right, thanks. check.py hasn't changed since we added the new gui (PyQT + OpenGL)
I've added checks for the two to check.py

**Comment by jooste** [comment]
Can you tell me a bit more about why you had to reinstall PyQt4? And are you using PyQt4 and PyQt5 simultaneously?

Thanks!

**Comment by espinielli** [comment]
after I installed `PyQt5` I got the following (or at least this is the earliest I find in my terminal):

```bash
$ python BlueSky.py
Reading config from settings.cfg
Using Qt5 for windows and widgets
Reading waypoints.dat from global
     74160 waypoints read.
Reading airports.dat from global
     14480 airports read.
Reading fir subfolder 36  FIRS read.
QGLWidget initialized for OpenGL version 3.3
Initializing multi-threaded simulation
Traceback (most recent call last):
  File "c:\repos\bluesky\bluesky\ui\qtgl\gui.py", line 330, in notify
    self.radarwidget.previewpoly(None)
  File "c:\repos\bluesky\bluesky\ui\qtgl\radarwidget.py", line 564, in previewpoly
    self.polyprev.set_vertex_count(0)
AttributeError: 'RadarWidget' object has no attribute 'polyprev'
Stopping Threads
BlueSky normal end.
```

Then after installing PyQt4 and re-running the error disappeared...
I do not know how much reproducible this is...maybe it can be proved with a clean machine.
HTH

**Comment by jooste** [comment]
Ok, what happened there is that the radarwidget is getting mouse events before it is initialized. This might be a machine-specific thing because it never happened on the machines I've tested it on (both Qt4 and Qt5). I've patched the BlueSky gui  event handler to check if radarwidget is initialized before sending it such events. This should (hopefully) fix your bug with Qt5.
