### ISSUE TITLE
[BUG] Old synthetics "super" routine not crossing through center

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#30]
The super routine generates traffic not crossing through the center of the circle.
![superbug](https://cloud.githubusercontent.com/assets/3062446/14981115/4168e590-112d-11e6-84f3-136f5e408d7d.PNG)

This is because of integer division of angles instead of floats in:
https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/stack/synthetic.py#L96

Can some-one about to do a commit or merge change the "360-360" part into "360.-360." in the above line?

Note! Previously generated synthetic super scenario files are wrong because of this.

**Comment by jooste** [comment]
Fixed in commit ad306a1
