### ISSUE TITLE
[BUG] exported scenario files (stack.saveic) not always readable

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#31]
The [saveic function in stack](https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/stack/stack.py#L504) does sometimes save a lat/lon coordinate in scientific notation when dealing with near-zero values. The stack cannot handle this format when reading in the scenario file and skips the argument:

![bug1](https://cloud.githubusercontent.com/assets/3062446/15049134/2845b770-12ed-11e6-9c4d-a263738d4cf1.PNG)

One way to solve this is by formatting the exported values, the below example does this by setting the precision to a 10 point float. 
https://github.com/pdanneels/bluesky/blob/synthetics/bluesky/stack/stack.py#L308

This however replaces the initial repr functions! @jooste @ProfHoekstra Do you know of any implications this might have?

**Comment by jooste** [comment]
Fixed in 342843e.
