### ISSUE TITLE
AttributeError: 'RadarWidget' object has no attribute 'globaldata'

### ISSUE THREAD

**Issue by 341O9O** [ProfHoekstra/bluesky#37]
Hello !

I have an issue running Bluesky with Pyqt4. Here is the entire output before python crashes : 

Initializing multi-process simulation
QGLWidget initialized for OpenGL version 3.3
Reading config from settings.cfg
OpenGL context created with GL version 2.1
Traceback (most recent call last):
  File "/Users/username/Desktop/bluesky-master/bluesky/ui/qtgl/radarwidget.py", line 557, in resizeGL
    self.globaldata.set_win_width_height(self.width, self.height)
AttributeError: 'RadarWidget' object has no attribute 'global data'

Do you have any idea of the reasons of such an error.

The soft is running perfectly well with pygame.
Thanking you by advance for your help.

**Comment by jooste** [comment]
Hello,

Can you tell me the make/model of your videocard, and the version of your PyOpenGL?

The output you show reports that the max supported GL version it could create a context for is v2.1. BlueSky needs at least GL version 3.3.

Cheers,
Joost

**Comment by 341O9O** [comment]
Hello ! 

Thanks for such a quick answer.
I have an Intel Iris 6100 (MBP). 
My version of PyOpenGL is 3.1.0.

Victor :)

**Comment by jooste** [comment]
Hi Victor,

Ok, your Mac is definitely recent enough, and PyOpenGL also should be ok, from 3.1.0 on up. How did you install python? Is it Anaconda? or did you install through macports? I use PyQt5, but it should also work with PyQt4.

**Comment by jooste** [comment]
Ok, I looked around a bit, I think this is a OSX+Qt4 issue. Qt4 works well on Windows and Linux, but runs into trouble on OSX, because of OSX peculiarities. 

Some install tips:
Macports: sudo port install py27-pyqt5
Anaconda: conda install -c spyder-ide pyqt5

Please let me know if this solved your problem!

**Comment by 341O9O** [comment]
Hi !

I use PIP for all installations concerning python. I'm going to install pyqt5. 
I'll inform you if my problem is solved.

Many Thanks.

**Comment by jooste** [comment]
Hi Victor,

Can you let me know if you've already had the chance to check this?

Thanks!

**Comment by jooste** [comment]
Update: this is a confirmed problem with PyQt4 on Mac OSX, see e.g. http://stackoverflow.com/questions/25708478/pyqt4-opengl-enabling-opengl-core-profile

Updating to PyQt5 solves the problem.
