### ISSUE TITLE
[BUG] pygame version broken

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#38]
Bug introduces in: 3ebc7f8

Now needs to load data only available to Qt version.

Problem: [loaddata.py](https://github.com/ProfHoekstra/bluesky/blob/3ebc7f8eb11ca624057d4d7e10b31ad422c54f0b/bluesky/tools/loaddata.py#L72)
Requires: [loaddata.py](https://github.com/ProfHoekstra/bluesky/blob/3ebc7f8eb11ca624057d4d7e10b31ad422c54f0b/bluesky/tools/loaddata.py#L10-L11)

The problem stretches beyond the loaddata module, the libraries used also check which GUI is enabled and do not load the required functions.

The bug breaks the pygame version completely as it is not able to start.

**Comment by ProfHoekstra** [comment]
Cannot reproduce this. Pygame version works fine with me. Must be specific problem in changed files, not in master version.

**Comment by pdanneels** [comment]
This is a screenshot of a clone into the ProfHoekstra master branch done just now into an empty directory. 

![image](https://cloud.githubusercontent.com/assets/3062446/16484801/8f7887a2-3ebb-11e6-941f-52347a073ef5.png)

The PC is not Qt - capable and the only thing I did was copy my pygame-enabled-settings file into the main directory.

Still the same error in the debugger:

![image](https://cloud.githubusercontent.com/assets/3062446/16484729/187f3c18-3ebb-11e6-809c-ca5b45cd3116.png)

**Comment by jooste** [comment]
Fixed in cb1f643
