### ISSUE TITLE
Pygame version broken, error in load_visuals_txt.py

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#58]
Import in [load_visuals_txt.py](https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/tools/load_visuals_txt.py#L71) only loaded in Qt block but also needed by pygame. 

Solution:
Make imports global: move line 71 and 72 to top of file.

**Comment by jooste** [comment]
Fixed in 04aeec4.
