### ISSUE TITLE
Untangeling research area from metrics instance

### ISSUE THREAD

**Issue by pdanneels** [ProfHoekstra/bluesky#6]
The research area functions called by the AREA command use the METRICS instance to save some data.

Wouldn't it be best to untangle those? In my opinion the AREA command is should not require an enabled METRICS module.

In my last pull request I fixed this by always issuing the command "METRICS ON" at startup to create the metrics instance.

**Comment by jooste** [comment]
Area was improved, and changed into a separate class in af86c49.
