### ISSUE TITLE
DDS texture compression is not supported

### ISSUE THREAD

**Issue by zhanggd** [ProfHoekstra/bluesky#67]
I used pyqt5 to run Bluesky on Fedora 25 (switched to X11) and got a warning like this: 
Warning:
QGLContext::bindTexture(): DDS texture compression is not supported.
Could anyone give some hints on how to resolve this? 

The configuration with pygame runs fine. Thanks

**Comment by jooste** [comment]
Hello,

I think that either you aren't running hardware-accelerated opengl but MesaGL, or your hardware doesn't support texture compression (unlikely, texture compression has been around for a long time). Can you tell me the model of your video card, and what video driver you use?. With the command glxinfo you can determine what is used for GL rendering, and which extensions are supported. BlueSky requires at least support for OpenGL version 3.3.
