### ISSUE TITLE
More details for BADA files installation instructions

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#68]
I would like to flag the need for more detailed info on BADA usage, i.e. in `data/coefficients/BADA/README_BADA.txt`
From the [perfbada.py](https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/traf/perfbada.py#L3) code it looks like I only need `OPF` files...

**Comment by espinielli** [comment]
It would also be nice to have some feedback in stdout whether BADA is being used or not.

**Comment by jooste** [comment]
Dear Enrico,

Thanks for the suggestions. The performance library in BlueSky is one of the things we want to improve soon. We will also try to make the feedback to stdout more clear.

**Comment by jooste** [comment]
Thanks for the commit (74de397)! I've also added an additional print statement so that it now always clear which performance model is used (see 47bc281).
