### ISSUE TITLE
improve message on aircraft performance

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#69]
I am using scenario `0-demo-scenario.scn` with BADA 3.1 and I get the following on stdout:

> aircraft is using default aircraft performance (Boeing 747-400)

I see that message in 2 places in the code, in [perfbada.py](https://github.com/ProfHoekstra/bluesky/blob/b6d29c20cdfbcdd946580b93543c2e99a10adf98/bluesky/traf/perfbada.py#L546) and [perf.py](https://github.com/ProfHoekstra/bluesky/blob/0a6903185e9bfe95c955a344f1a8c3b27dc6d220/bluesky/traf/perf.py#L438)

I assume I hit the `perfbada.py` code (see #68 for a request to provide the contextual info), then what does the message mean? Is a certain flight in the scenario specified with an aircraft model not in the BADA ones?
If so, which one? I.e. which ID, line in the scenario...

**Comment by jooste** [comment]
Dear Enrico,

First of all thanks for your comments and suggestions! The performance implementation of BlueSky is indeed in need of some improvement. We also want to work on a more thorough basic-use manual.

That message means that BlueSky is not using BADA. This can have two reasons: either you have not selected BADA as a performance (check your settings.cfg in the root of your BlueSky folder, and look for the setting called 'performance_model', this should be set to 'bada' if you want to use bada.)

Another reason could be that BlueSky can't find the BADA data files. The path where BlueSky looks for that is also given in your settings.cfg file ('perf_path').

**Comment by espinielli** [comment]
@jooste I changed `performance_model` from `'bluesky'` to `'bada'` and left `'perf_path_bada'` to its default value of `data_path + '/coefficients/BADA'` (I suppose you mentioned `perf_path_bada` rather than `perf_path` above...given I am using BADA model) but I get the same message on stdout.

**Comment by jooste** [comment]
Dear Enrico,

I made a mistake in my original message, the stdout message you mention indicates that an aircraft was created without specifying an aircraft model. In that case BlueSky uses the default, which is a B747-400.

The settings.cfg change is still a good change to make though. Do you get any additional messages in stdout now, when you start BlueSky? If it says 'Falling back to BlueSky performance model', it wasn't able to find your BADA files. Otherwise it should be using BADA. We'll add more informative messages soon! :)

**Comment by espinielli** [comment]
With the setting as above when loading `0-demo-scenario.scn` I still get (as in the initial essay):

```shell
c:\repos\bluesky>python BlueSky.py
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Reading config from settings.cfg
Loading global navigation database...
Reading cache: navdata.p
Reading cache: rwythresholds.p

Setting up screen...
Reading coastlines.dat
     230912  coastlines added.
Setting up Traffic simulation
Opening  C:\repos\bluesky\scenario\0-demo-scenario.scn
aircraft is using default aircraft performance (Boeing 747-400).

```

**Comment by jooste** [comment]
Yes, this is correct. 0-demo-scenario doesn't specify aircraft models for the created aircraft, which is why that message is printed. If you specified 'bada' in your configuration before you ran this, then this printout also means that loading the BADA files succeeded (no error message). I have added a positive message as well when the BADA performance model successfully loads in commit 8a60bff.

**Comment by espinielli** [comment]
So I put the debugger on just before the print of the message and found out that BADA is not loaded...the debugger kicks in at `perf.py` and not `perf_bada.py`...my settings:

```python
# Select the performance model. options: 'bluesky', 'bada'
performance_model = 'bada'

# Indicate the datafile path
data_path = 'data'

# Indicate the logfile path
log_path = 'output'

# Indicate the scenario path
scenario_path = 'scenario'

# Indicate the path for the aircraft performance data
perf_path = data_path + '/coefficients/BS_aircraft'

# Indicate the path for the BADA aircraft performance data (leave empty if BADA is not available)
perf_path_bada = data_path + '/coefficients/BADA'


```

**Comment by jooste** [comment]
When I run BlueSky with performance_model = 'bada' I get the following message in stdout:

BADA performance model: No BADA files found in data/coefficients/BADA!
Falling back to BlueSky performance model

This is correct behavior when there are no .OPF files in your specified BADA path. When I put OPF files there the bada performance model is loaded. If you update to the latest version on GitHub, do you still not get any message about bada? (either positive or negative)

**Comment by espinielli** [comment]
Pulled latest from repo, removed any other file by `.OPF`, checked that the code I see changed, and I still get:

```shell
c:\repos\bluesky>python BlueSky.py
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Reading config from settings.cfg
Loading global navigation database...
Reading cache: navdata.p
Reading cache: rwythresholds.p

Setting up screen...
Reading coastlines.dat
     230912  coastlines added.
Setting up Traffic simulation
Opening  C:\repos\bluesky\scenario\0-demo-scenario.scn
aircraft is using default aircraft performance (Boeing 747-400).

```
I thought this was due to [line 48 of `perfbada.py`](https://github.com/ProfHoekstra/bluesky/blob/8a60bff254f6131907949006f7edc4b07f9e50e4/bluesky/traf/perfbada.py#L48) not using `perf_path_bada` but even changing that does not change my results...

weird...I will clone again and start from scratch...

**Comment by espinielli** [comment]
Now BADA is loaded, but it crashes

```shell
C:\repos\bluesky>python BlueSky.py
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Reading config from settings.cfg
Using BADA performance model. Found 195 aircraft performance definition files (*.OPF)
Loading global navigation database...
Reading cache: navdata.p
Reading cache: rwythresholds.p

Setting up screen...
Reading coastlines.dat
     230912  coastlines added.
Setting up Traffic simulation
Opening  C:\repos\bluesky\scenario\0-demo-scenario.scn
Traceback (most recent call last):
  File "BlueSky.py", line 19, in <module>
    bs.MainLoop()
  File "C:\repos\bluesky\BlueSky_pygame.py", line 34, in MainLoop
    sim.update(gui.scr)  # Update sim
  File "C:\repos\bluesky\bluesky\sim\pygame\simulation.py", line 118, in update
    stack.process(self, self.traf, scr)
  File "C:\repos\bluesky\bluesky\stack\stack.py", line 1143, in process
    results = function(*arglist)  # * = unpack list to call arguments
  File "C:\repos\bluesky\bluesky\traf\traffic.py", line 268, in create
    self.perf.create()
  File "C:\repos\bluesky\bluesky\traf\perfbada.py", line 594, in create
    self.cascl        = np.append(self.cascl, coeff.cascl[self.coeffidx]*kts)
IndexError: list index out of range
```

**Comment by jooste** [comment]
Could it be that you have only OPF files installed? coeff.cascl comes out of the .APF files, but currently the bada implementation just assumes that every OPF file is accompanied by a APF file. This will be made more robust, but its going to take a bit of work and time :)

**Comment by espinielli** [comment]
Aaaah,
I misinterpreted your comments about OPF files and assumed only those were
necessary...and removed all the rest.
Waiting for some checks in the code I would suggest a little bit more
instructions in the Readme file in the BADA directory. Something like

"Copy the content of the badaxyzzy directory of the unzipped BADA  files,
i.e. .OPF .OPD .APT files,  in this directory"

I will eventually send a pull request...

On Jan 19, 2017 20:43, "Joost Ellerbroek" <notifications@github.com> wrote:

Could it be that you have only OPF files installed? coeff.cascl comes out
of the .APF files, but currently the bada implementation just assumes that
every OPF file is accompanied by a APF file. This will be made more robust,
but its going to take a bit of work and time :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ProfHoekstra/bluesky/issues/69#issuecomment-273877541>,
or mute the thread

**Comment by jooste** [comment]
Thanks! I will add more print statements where useful :)

**Comment by espinielli** [comment]
I slightly modified a [couple of lines](https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/traf/perfbada.py#L549-L550) in `perfbada.py` in order to see which flights are missing perf data in the  `` scenario.

Similarly in `perf.py` to log verbosely.
PR is coming
