### ISSUE TITLE
Info: Airspace intersection and occupancy counts

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#77]
Does BlueSky have any facility to perform 4D (3D + time, maybe 7D including speed vector) intersection with geo volums, i.e. airspaces?
This would allow for entry/exit or occupancy counts...useful for measuring sector load, simulating fatigue...

**Comment by jooste** [comment]
Well, we already have 3D area intersections in tools.areafilter, this should be at least a start to what you are looking for. We currently use it to filter log data, and delete aircraft that exit a particular area, or for instance only enable CD&R inside an area.

What do you mean by 4D? That the geometric shape depends on time? Or just that time is logged?

**Comment by espinielli** [comment]
3D because the shape of the airspace is a composition of polygons with
altitude bands.
4D because I need also the time component, i.e. when an aircraft
enters/exits an airspace: lon/lat/altitude/time

**Comment by jooste** [comment]
Ok. I think this is easily implemented using tools.areafilter, and the logging options in tools.datalog. I think one of the forks has already implemented a conditional logging using the areafilter, I'll have a look.

**Comment by ProfHoekstra** [comment]
For calculations 3D should be sufficient. When you have the 3D points which intersect, you can interpolate with the along-track distance and the time constraints in your trajectory to get the entry-exit times, then you have 4D. – Jacco Hoekstra

**Comment by espinielli** [comment]
But I haven't (yet) found any 3D support for airspace definition in the
bluesky code base.
In the data part I see FIRs are available as a 2D set of
coordinates...while I am interested in FIRs and UIRs so I will have a
vertical split.
Then speaking of more complicated airspaces, like Elementary Sectors, the
2D projection can change according to altitude...
Any hints as to where to check in the code if any is available?

**Comment by jooste** [comment]
Apologies for leaving this unaddressed for so long. Do you think you would be able to achieve what you require by using multiple areas as they are currently defined in BlueSky? (an area currently being a set of 2D horizontal lat/lon points, with a common lowalt and highalt). This way you can at least create shelves in airspace designs, but more complicated 3D shapes like vertical slopes are not possible. This would require full-fledged 3D polygons, but this seems, on first sight, to be a bit overkill.

**Comment by espinielli** [comment]
Thanks. 
To my knowledge there are no vertical slopes in airspaces, at least in Europe as seen by EUROCONTROL's Network Manager. 
So what available in BlueSky seems to suffice. 
I'll check code/examples for ways use that functionality. 
PS: I am sorry too for having left other reported issues unattended (i.e. the one on OSX installation...I will try to get back on it)

**Comment by jooste** [comment]
Since recently, BlueSky offers the opportunity to make and use self-contained plugins in the simulation. As a starting point, I've created a small example of a sector occupancy count plugin [here](https://github.com/ProfHoekstra/bluesky/blob/master/plugins/sectorcount.py). To test it, try the following in the BlueSky console:

    PLUGINS LOAD SECTORCOUNT
    POLY SEC <list of lat/lon points, you can click on the radar screen to add points>
    SECTORCOUNT ADD SEC
    MCRE 50
    FF

This loads the sectorcount plugin, creates a polygon sector with the coordinates you choose (just click a couple of them on the radar screen), and selects the new polygon as a sector for the plugin. Then, `MCRE` creates 50 random aircraft, and `FF` enables fast-time running.

Logging of occupancy counts is also already there in the plugin, just type `OCCUPANCYLOG ON`

**Comment by jooste** [comment]
@espinielli @ProfHoekstra, I think the previous update to this issue was not sent around as the issue is closed. Please have a look at my previous comment for an easy solution to sector occupancy counts in BlueSky.
