### ISSUE TITLE
Flickering WPT

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#78]
(Sorry to bother.)
Using QT version of BlueSky I get flickering WPT, see video

![out](https://cloud.githubusercontent.com/assets/891692/22257843/882c6ad4-e25f-11e6-9cf0-e2fb417aefa2.gif)

Flickering happens even when you load a scenario.

**Comment by jooste** [comment]
Wow, never seen anything like that before! I think this is on your mac, right? Can you tell me more about the model, age, and whether it has discrete graphics? Something seems to be going (seriously) wrong with OpenGL. The text labels aren't correct at all, even if they would not be flickering. I also notice that you don't have the map texture? Or did you turn it off for the movie? Did any warning or error show up in the terminal?

**Comment by espinielli** [comment]
I turned the map off just to highlight the problem...nothing showed up on the terminal.

Here is my (old-ish) Mac info:
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro5,5
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.53 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	8 GB
  Bus Speed:	1.07 GHz
...
NVIDIA GeForce 9400M:

  Chipset Model:	NVIDIA GeForce 9400M
  Type:	GPU
  Bus:	PCI
  VRAM (Total):	256 MB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0863
  Revision ID:	0x00b1
  ROM Revision:	3427
  Displays:
Color LCD:
  Display Type:	LCD
  Resolution:	1280 x 800
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes

**Comment by jooste** [comment]
Well, I'm actually a bit surprised that it started at all! From what I can find the 9400M should indeed be able to support OpenGL 3.3 (the minimum for BlueSky). The fact that you do see things like the airport symbols indicates that indeed GL3.3-specific functions like instanced rendering work. I think it could be two things: either it is still a compatibility issue, or a memory problem, BlueSky loads quite a few things into GPU memory. Although maybe not 256M, I'm not sure. It could be worth a shot to comment out the texture loading in radarwidget.py: comment out line 185. Another big chunk of GPU memory is taken by the taxiways/pavement drawing. You can remove these by commenting out lines 233-242 and lines 476-477.
