### ISSUE TITLE
 CRmethod("SWARM") ERROR

### ISSUE THREAD

**Issue by argguochen** [ProfHoekstra/bluesky#79]
Hi, I just tested CRmethod("SWARM") and I had a crash. 
-- Open "ASAS-01.scn",and modify "00:00:00.00>RESO MVP" to "00:00:00.00>RESO SWARM"
-- Some error messages appear in the log:

File "D:/bluesky-20161201/bluesky-20161201\bluesky\traf\asas \Swarm.py", line 39, in resolve
    MVP.resolve(dbconf)
TypeError: resolve() takes exactly 2 arguments (1 given)
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Process finished with exit code 1

-- Then I add a argument to the function like this:

# First do conflict resolution following MVP
MVP.resolve(dbconf,traf)

-- Some error messages also appear in the log:

File "D:/bluesky-20161201/bluesky-20161201\bluesky\traf\asas\Swarm.py", line 42, in resolve
    ca_trk = dbconf.active*dbconf.hdg+(1-dbconf.active)*traf.ahdg
AttributeError: 'ASAS' object has no attribute 'hdg'
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Process finished with exit code 1

-- Would you please tell me how to fix it?
-- The CD and CR algorithms, especially Swarm algorithm code(CRmethod) are a little bit too obscure, would you please provide some references of these algorithms.
-- Thanks.

**Comment by jooste** [comment]
Hi,
The crash is fixed in commit 77f8774. I'll ask the guy who made Swarm.py if he has some references for the method.

**Comment by jooste** [comment]
Here is a reference for the swarming method:
Chang-Su Park, Min-Jea Tahk, and Hyochoong Bang. Multiple Aerial Vehicle Formation Using Swarm Intelligence. In AIAA Guid. Navig. Control Conf., number August, page 8, Austin, 2003. Korea Advanced Institute of Science and Technology.

**Comment by argguochen** [comment]
Thank you very much

在 2017-05-23 20:26:04，"Joost Ellerbroek" <notifications@github.com> 写道：


Closed #79.
