### ISSUE TITLE
ADS-B datafeed setup documentation

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#9]
I see that in [adsb_datafeed.py](https://github.com/ProfHoekstra/bluesky/blob/master/bluesky/tools/adsb_datafeed.py) you can listen to  a cetain IP address/port to stream flight ADS-B readings.
Could you add some more documentation (in README? [Wiki](https://github.com/ProfHoekstra/bluesky/wiki)?) about how you use it?
What is the format?

I am interested in it because I was thinking whether it could be possible to feed historical ADS-B data which we have already decoded and archived in our DB and/or files...
Thanks in advance

**Comment by junzis** [comment]
Yes, this module need to be re-written. Currently it is a customized data protocol on top of a TCP stream. We will try to make it able to decode mode-s beast raw messages, and as well as Basestation format. 

Any other recommendations?

**Comment by espinielli** [comment]
I very much like the idea to feed ADS-B data, but I would not go into the trouble of implementing the decoding.
Just as an example you can buy a 10$ DVB-T dongle and use [dump1090](https://github.com/MalcolmRobb/dump1090) to decode the readings.

What is interesting is to propose a format to feed the simulator via TCP stram, then the scenario can be:

source (ADS-B realtime or archived or synthetic) -> formatter -> tcp host/port -> simulator

or 

synthetic stream of position/speed/id/... reports -> tcp host/port -> simulator

(when I use "->" I think of unix piping sort of)

**Comment by junzis** [comment]
We already built the decoding library in python, so decoding from raw message is not a trouble anymore:
https://github.com/junzis/py-adsb-decoder

I would approach it in two different ways.

1. For online ADS-B stream, the TCP server/client architecture is still the best practice. We do have a Mode-S Beast receiver setup with both raw data stream and dump1090 decoded data stream. I will soon push an updated version for streaming [Mode-S Beast raw bin data](http://wiki.modesbeast.com/Mode-S_Beast:Data_Output_Formats) and [SBS1](https://github.com/antirez/dump1090#port-30003) data format. (Stay tuned)

2. For offline ADS-B archives, we should simply use a script to convert it into scenario file. (to be implement later)

**Comment by espinielli** [comment]
Yes, I saw the code when I initially filed this issue.
The problem (i.e. cost) is usually maintaining it! Or even having to learn about it (for contributors/...)

So things that are not **core** to the simulator should IMHO be factored out: better to write analysis algorithms or a plug-in framework to let users select their own ones (...is that possible? Have you thought of it?), metrics collection (counts per volume [FIR, Sector, Collapsed sectors...])...

Even for online stream I would personally go for a third party (open source ;-) tool.

But the call is with you. All above is just my personal view.

I look forward to reading about your planned enhancements.

**Comment by junzis** [comment]
Yes, those are different approaches in software architectures. BlueSky is still in heavy developing cycles. We are including this function from streaming ADS-B in the main block for now. Perhaps in future we will need to separate core functions and extensions.

**Comment by junzis** [comment]
The ADS-B streaming should be working now if one has a Mode-s Beast TCP server setup. We will keep on working with other interfaces still.

**Comment by jooste** [comment]
Hi Enrico,

There are a couple of reasons why the ads-b decoder is currently part of the core code of the simulator. The most pragmatic one is that we are currently working a lot with ads-b data from our own antenna, and need an easy way to get access to live data in our simulator. We don't have a plugin structure yet. Maybe when we have more elements than just the ads-b decoding we'll have an idea of what the required generic plugin interface should look like.

However, some of the near-future work does include hooking up BlueSky to a human-in-the-loop simulation as a blip driver, for which we are making several generic TCP and UDP network I/O classes. The current ads-b class derives from one of these.

Thanks for your suggestions, we are always interested in new ideas and contributions.

Happy holidays!

**Comment by espinielli** [comment]
Hi Joost,
My suggestion, apart from sw design principles/experience, originates from
the desire to use the simulator at work, Performance Review Unit @
Eurocontrol.
We would like to replay (all European?) traffic and analize safety issues
or simulate scenarios in order to devise new performance indicators.
Of course the ability to replay decoded A-DSB reports is a prerequisite for
that kind of use.

I will keep an eye on the evolution of the simulator and would really
delighted to contribute in lines of code...but I know I will have little
time available to dedicate to anything like that... :-(

Bye
Enrico

**Comment by jooste** [comment]
Hi Enrico,

Chances are that we already have something quite close to the conversion tool you would need. Previously one of our students who worked with BlueSky created a script to convert from so6 files (Eurocontrol DDR) to bluesky scenario files. Depending on how your data are formatted the script you need will be very similar.

Best,
Joost

**Comment by espinielli** [comment]
Joost,
Good that goes in the direction I am more interested in.
Still it would be great to feed whatever (position reports [but then why
not simu commands]) on a tcp port...

Thanks
Bye
Enrico
PS: we are not currently using DDR files. We are more into post-OPS
analysis, i.e. measuring/making sense of the past (in order to make the
future better ;-)
