### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by denzilsaldanha** [ProfHoekstra/bluesky#90]
Hello,
Sorry to disturb

I've been trying to use the release version of bluesky for the first time and i keep getting this error whenever i use the IC command to access the demo file. It even comes when i try to open it from file>open and select demo. 

Traceback (most recent call last):
  File "bluesky\sim\qtgl\mainmanager.py", line 196, in event
IndexError: list index out of range

**Comment by ProfHoekstra** [comment]
Thank you for this report, we will have a look at this and get back to you. What is your OS?

IC should work with file name-completion, or without arguments to select a file with the dialog box. Alternatively you can also try the pull-down menu: File > Open.

If this also does not work, you could temporarily try to use the pygame version(bluesky-pygame.py), while we solve this issue.

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 25 Jun 2017, at 11:53, denzilsaldanha <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
Sorry to disturb

I've been trying to use the release version of bluesky for the first time and i keep getting this error whenever i use the IC command to access the demo file. It even comes when i try to open it from file>open and select demo.

Traceback (most recent call last):
File "bluesky\sim\qtgl\mainmanager.py", line 196, in event
IndexError: list index out of range

**Comment by denzilsaldanha** [comment]
I'm working on Windows 10. I did try the pull-down menu only to get the same result
Here is a screenshot of the error I'm getting

Thanks for the help 

![screenshot 3](https://user-images.githubusercontent.com/19554277/27526052-a8f531be-5a60-11e7-8e94-1d439ed848bd.png)

**Comment by ProfHoekstra** [comment]
Unfortunately I cannot replicate this error in the latest version, this issue does not occur there. The solution is that we make a new release. In the meantime you could try to use the standard version e.g. by choosing “download as zip-file”  (which does require installing Python, see installation instructions in the Wiki.) Then you always have the latest version.

**Comment by denzilsaldanha** [comment]
I downloaded the zip file only to get the same error. I even ran check.py 


![screenshot 4](https://user-images.githubusercontent.com/19554277/27539296-97e1458c-5a99-11e7-96e4-ed8ba5bfe061.png)

**Comment by ProfHoekstra** [comment]
And does the Pygame version run?

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 26 Jun 2017, at 14:33, denzilsaldanha <notifications@github.com<mailto:notifications@github.com>> wrote:


I downloaded the zip file only to get the same error. I even ran check.py

[screenshot 4]<https://user-images.githubusercontent.com/19554277/27539296-97e1458c-5a99-11e7-96e4-ed8ba5bfe061.png>

**Comment by denzilsaldanha** [comment]
The pygame version runs fine.
The data>global file was missing from the 'bluesky-master' version so i copied it from the bluesky release. It works fine now.

**Comment by jooste** [comment]
with regard to the qtgl version, could it be that your firewall is blocking the connection between the simulation process and the gui process? TCP is used for this connection, so if your firewall is strict the qtgl version of bluesky won't work.

**Comment by denzilsaldanha** [comment]
Yes. I upgraded the permissions, that solved the problem. Thanks a lot!
