### ISSUE TITLE
Use of TCP port

### ISSUE THREAD

**Issue by reube** [ProfHoekstra/bluesky#91]
Hi - trying to issue commands over TCP (8888)
I notice in the code that my commands make it on to a command stack, but they never seem to be processed.

I get this far in `stack.py`
```
def stack(cmdline):
    # Stack one or more commands separated by ";"
    cmdline = cmdline.strip()
    if len(cmdline) > 0:
        for line in cmdline.split(';'):
            print line   # my addition
            cmdstack.append(line)
```

but I don't get this far:
```
def process():
    """process and empty command stack"""
    global cmdstack

    # Process stack of commands
    for line in cmdstack:
        print "processing:" + line   # my addition
```

Could you advise on use of the network interface? :+1: 

Many thanks

**Comment by jooste** [comment]
It seems you found a bug that was caused by some previous restructuring of the BlueSky code. I've fixed the problem in commit 73b414e. Thanks for finding this problem :)
