### ISSUE TITLE
Runways list is rendered incorrectly in console

### ISSUE THREAD

**Issue by jacobythwaites** [ProfHoekstra/bluesky#95]
The runways list obtained by a command such as `POS EHAM` includes undesirable `u` prefixes.

See attached screenshot.

`git apply runways.txt` below to fix.

[runways.txt](https://github.com/ProfHoekstra/bluesky/files/1214846/runways.txt)

![image](https://user-images.githubusercontent.com/2727822/29170120-0a1e5a92-7dcf-11e7-910b-bac038b65101.png)

**Comment by jooste** [comment]
Thanks! Patch is applied in commit 0f29f4e.
